server:
  port: ${EUREKA_PORT}

eureka:
  instance:
    hostname: ${EUREKA_HOST}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
