server:
  port: 8081


# Eureka client config
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http:localhost:8761/eureka}$

management:
  tracing:
    sampling:
      probability: 1.0   # trace all requests
  endpoint:
    web:
      exposure:
        include: "*" # Expose all actuator endpoints
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URI:http://localhost:9411/api/v2/spans}
