server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/usersdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: local_user
    password: local_password
    hikari:
      pool-name: UserSvcHikariPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000 # 30 seconds
      idle-timeout: 60000 # 10 minutes
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis
    redis:
      time-to-live: 60000

  # SQL initialization
  sql:
    init:
      mode: always  # run data.sql to populate the mysql database
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
      platform: mysql

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    user.service.userservice: INFO
    org.hibernate.SQL: INFO

# Eureka client config
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

grpc:
  server:
    port: 9090